// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClass = "class"

// Class 班级信息表
type Class struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:班级ID" json:"id"`               // 班级ID
	GradeYearID int64     `gorm:"column:grade_year_id;not null;comment:年级学年ID（逻辑外键）" json:"grade_year_id"`      // 年级学年ID（逻辑外键）
	Name        string    `gorm:"column:name;not null;comment:班级名称，例如 1班、2班" json:"name"`                       // 班级名称，例如 1班、2班
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"updated_at"` // 最后更新时间
	CreatedBy   string    `gorm:"column:created_by;default:admin;comment:创建人ID" json:"created_by"`              // 创建人ID
	UpdatedBy   string    `gorm:"column:updated_by;default:admin;comment:最后修改人ID" json:"updated_by"`            // 最后修改人ID
}

// TableName Class's table name
func (*Class) TableName() string {
	return TableNameClass
}
