// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAfCampaign = "af_campaign"

// AfCampaign mapped from table <af_campaign>
type AfCampaign struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GameID       int32   `gorm:"column:game_id;not null" json:"game_id"`
	Dt           int32   `gorm:"column:dt;not null" json:"dt"`
	DataType     string  `gorm:"column:data_type;not null;comment:日、周、月" json:"data_type"` // 日、周、月
	Platform     string  `gorm:"column:platform;not null" json:"platform"`
	Country      string  `gorm:"column:country;not null" json:"country"`
	MediaSource  string  `gorm:"column:media_source;not null" json:"media_source"`
	AdType       string  `gorm:"column:ad_type;not null" json:"ad_type"`
	Campaign     string  `gorm:"column:campaign;not null" json:"campaign"`
	CampaignID   string  `gorm:"column:campaign_id;not null" json:"campaign_id"`
	Nu           int32   `gorm:"column:nu;not null" json:"nu"`
	Rev0         float64 `gorm:"column:rev0;not null" json:"rev0"`
	Rev1         float64 `gorm:"column:rev1;not null" json:"rev1"`
	Rev7         float64 `gorm:"column:rev7;not null" json:"rev7"`
	Rev30        float64 `gorm:"column:rev30;not null" json:"rev30"`
	Ua1          int32   `gorm:"column:ua1;not null" json:"ua1"`
	Ua7          int32   `gorm:"column:ua7;not null" json:"ua7"`
	Ua30         int32   `gorm:"column:ua30;not null" json:"ua30"`
	TdIaprev     float64 `gorm:"column:td_iaprev;not null" json:"td_iaprev"`
	TdIaarev     float64 `gorm:"column:td_iaarev;not null" json:"td_iaarev"`
	DeviceLaunch int32   `gorm:"column:device_launch;not null" json:"device_launch"`
	Click        int32   `gorm:"column:click;not null" json:"click"`
	Cost         float64 `gorm:"column:cost;not null" json:"cost"`
	Impression   int32   `gorm:"column:impression;not null" json:"impression"`
	TotalCost    float64 `gorm:"column:total_cost;not null" json:"total_cost"`
	TotalDays    int32   `gorm:"column:total_days;not null" json:"total_days"`
	TotalNu      int32   `gorm:"column:total_nu;not null" json:"total_nu"`
	TotalIaarev  float64 `gorm:"column:total_iaarev;not null" json:"total_iaarev"`
	TotalIaprev  float64 `gorm:"column:total_iaprev;not null" json:"total_iaprev"`
}

// TableName AfCampaign's table name
func (*AfCampaign) TableName() string {
	return TableNameAfCampaign
}
