// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGrade = "grade"

// Grade 年级类型表
type Grade struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:年级ID" json:"id"`               // 年级ID
	Name      string    `gorm:"column:name;not null;comment:年级名称，例如 高一、初三" json:"name"`                       // 年级名称，例如 高一、初三
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"updated_at"` // 最后更新时间
	CreatedBy string    `gorm:"column:created_by;default:admin;comment:创建人ID" json:"created_by"`              // 创建人ID
	UpdatedBy string    `gorm:"column:updated_by;default:admin;comment:最后修改人ID" json:"updated_by"`            // 最后修改人ID
}

// TableName Grade's table name
func (*Grade) TableName() string {
	return TableNameGrade
}
