// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAcademicYear = "academic_year"

// AcademicYear 学年信息表
type AcademicYear struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:学年ID" json:"id"`               // 学年ID
	Name      string    `gorm:"column:name;not null;comment:学年名称，例如 2025-2026" json:"name"`                   // 学年名称，例如 2025-2026
	StartDate time.Time `gorm:"column:start_date;comment:学年开始日期" json:"start_date"`                           // 学年开始日期
	EndDate   time.Time `gorm:"column:end_date;comment:学年结束日期" json:"end_date"`                               // 学年结束日期
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"updated_at"` // 最后更新时间
	CreatedBy string    `gorm:"column:created_by;default:admin;comment:创建人ID" json:"created_by"`              // 创建人ID
	UpdatedBy string    `gorm:"column:updated_by;default:admin;comment:最后修改人ID" json:"updated_by"`            // 最后修改人ID
}

// TableName AcademicYear's table name
func (*AcademicYear) TableName() string {
	return TableNameAcademicYear
}
