// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGradeYear = "grade_year"

// GradeYear 年级与学年的对应关系表
type GradeYear struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:年级学年关联ID" json:"id"`           // 年级学年关联ID
	GradeID        int64     `gorm:"column:grade_id;not null;comment:年级ID（逻辑外键）" json:"grade_id"`                  // 年级ID（逻辑外键）
	AcademicYearID int64     `gorm:"column:academic_year_id;not null;comment:学年ID（逻辑外键）" json:"academic_year_id"`  // 学年ID（逻辑外键）
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"updated_at"` // 最后更新时间
	CreatedBy      string    `gorm:"column:created_by;default:admin;comment:创建人ID" json:"created_by"`              // 创建人ID
	UpdatedBy      string    `gorm:"column:updated_by;default:admin;comment:最后修改人ID" json:"updated_by"`            // 最后修改人ID
}

// TableName GradeYear's table name
func (*GradeYear) TableName() string {
	return TableNameGradeYear
}
