// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package system

import (
	"time"
)

const TableNameSystemUser = "system_user"

// SystemUser 系统用户表
type SystemUser struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:系统用户ID" json:"id"`             // 系统用户ID
	Name      string    `gorm:"column:name;not null;comment:用户名" json:"name"`                                 // 用户名
	Email     string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                // 邮箱
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`                          // 密码
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"updated_at"` // 最后更新时间
	CreatedBy string    `gorm:"column:created_by;default:admin;comment:创建人ID" json:"created_by"`              // 创建人ID
	UpdatedBy string    `gorm:"column:updated_by;default:admin;comment:最后修改人ID" json:"updated_by"`            // 最后修改人ID
}

// TableName SystemUser's table name
func (*SystemUser) TableName() string {
	return TableNameSystemUser
}
